### ISSUE TITLE
Font 32 bpp support

### ISSUE THREAD

**Issue by coldev** [dacucar/fenixlib#14]
Thanks for this Project..

PLease add Font 32bpp support (write/read), currently open font not work in windows forms example

i have a unsupported format exception, 32bpp, open 32bpp font is supported? thanks...

My Fonts to test...

[http://www.mediafire.com/download/aaktnygv20rmmgg/test_fonts.rar](http://www.mediafire.com/download/aaktnygv20rmmgg/test_fonts.rar)

or share a Executable from your UI fpg editor to include in Bennupack..    thanks

```
FenixLib.Core.UnsuportedFileFormatException: Error de E/S.
   en FenixLib.IO.NativeDecoder`1.Decode(Stream input) en C:\desarrollo\NET\fenixlib-master\FenixLib\FenixLib\IO\NativeDecoder.cs:línea 158
   en FenixLib.IO.NativeFile.LoadFnt(String path) en C:\desarrollo\NET\fenixlib-master\FenixLib\FenixLib\IO\NativeFile.cs:línea 102
   en FenixLibAndWindowsFormsExample.Form1.button3_Click(Object sender, EventArgs e) en C:\desarrollo\NET\fenixlib-master\FenixLib\Examples\FenixLibAndWindowsForms\Form1.cs:línea 86
   en System.Windows.Forms.Control.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   en System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.ButtonBase.WndProc(Message& m)
   en System.Windows.Forms.Button.WndProc(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by dacucar** [comment]
There is support for 32bpp fonts both read and write. I will test your files and come back with more info.

How was the font generated?

The FPG UI is just a draft so there is nothing to share.

**Comment by coldev** [comment]
thanks 4 reply

hmm fonts crash when loading.. (pixtudio load fonts ok, is weird).

Pixtudio examples include this fonts...

we improve a fpg example please include in your examples...

there a fpg editor improved  .. thanks for the lib...

https://sourceforge.net/projects/coldev/files/bennugd2_Pixtudio/v1.4/sourcecodeTools/

**Comment by dacucar** [comment]
Hi,

I found the source of the problem. It is actually two problems: on one side, the code of the example that uses TryDecode with the DivFntBitmapFontDecoder is not closing the stream before attempting to read it with the ExtendedBitmapFontDecoder.

So I changed NativeFile.cs

`
        public static IBitmapFont LoadFnt ( string path )
        {
            // DivFont decoder is used by default
			var divFontDecoder = new DivFntBitmapFontDecoder ();

            using ( var stream = File.Open ( path, FileMode.Open ) )
            {
                IBitmapFont font;
                if ( divFontDecoder.TryDecode ( stream, out font ) )
                {
					return font;
                }
            }

			// Fallback to the ExtendedFontBitmapFontDecoder
			var extendedFontDecoder = new ExtendedFntBitmapFontDecoder ();

			using ( var stream = File.Open ( path, FileMode.Open ) )
			{
				return extendedFontDecoder.Decode ( stream );
			}
        }
`
But even with this the program will fail to read Font files that are compressed. The reason is because of the use of the "Position" property in the stream, which seems to not be supported for compressed files.

When the font is not compressed, the decoding works:

![screenshot_2016-09-01_15-36-14](https://cloud.githubusercontent.com/assets/17236823/18169336/f75b3fa2-7059-11e6-82b6-26ae8626e316.png)

**Comment by dacucar** [comment]
I will have a look at your improved Fpg editor example (I already tried the binary version), thanks for the report and your contribution.

**Comment by dacucar** [comment]
Moved to #15 and #16
